web/CrailLms/config/routes.rb
Rails.application.routes.draw do

  resources :announcements, except: [:index, :show]

  resources :deliverables, except: [:index]
  resources :assignments, controller: 'deliverables', type: 'Assignment'
  resources :quizzes, controller: 'deliverables', type: 'Quiz'
  resources :tutorials, controller: 'deliverables', type: 'Tutorial'

  resources :resources, except: [:index]
  resources :urls, controller: 'resources', type: 'Url'
  resources :videos, controller: 'resources', type: 'Video'
  resources :documents, controller: 'resources', type: 'Document'

  resources :course_registrations do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :user_registrations do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :courses do
    post 'register', on: :member
    post 'withdraw', on: :member
    post 'create_announcement', on: :member
    post 'update_grade', on: :member
  end

  resources :users
  resources :teachers, controller: 'users', type: 'Teacher'
  resources :admins, controller: 'users', type: 'Admin'
  resources :students, controller: 'users', type: 'Student'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'pages/home'

  root to: 'pages#home'
end

web/CrailLms/app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :course
  self.abstract_class = true
end

web/CrailLms/app/models/admin.rb
class Admin < User
end

web/CrailLms/app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :announcement_manager
end

web/CrailLms/app/models/assignment.rb
class Assignment < Deliverable
end

web/CrailLms/app/models/course.rb
class Course < ApplicationRecord
  belongs_to :semester
  belongs_to :teacher
  has_many :course_registrations, dependent: :delete_all
  has_many :users, -> { where(course_registrations: { status: "approved" }) }, through: :course_registrations
  has_many :deliverables
  has_many :resources
  has_many :announcements
  has_one :announcement_manager
  after_create :setup_announcement_manager

  def enrolled_students
    CourseRegistration.where(course_id: id, status: "approved").count
  end

  def pending_registration?(user_id)
    !CourseRegistration.where(course_id: id, user_id: user_id, status: "pending").empty?
  end

  def registered?(user_id)
    !CourseRegistration.where(course_id: id, user_id: user_id, status: "approved").empty?
  end

  def setup_announcement_manager
    create_announcement_manager
    self.announcement_manager_id = AnnouncementManager.last.id
  end
end

web/CrailLms/app/models/deliverable.rb
class Deliverable < Activity
  has_many :submissions, dependent: :delete_all
end

web/CrailLms/app/models/department.rb
class Department < ApplicationRecord
  has_many :course
  has_many :teacher
end

web/CrailLms/app/models/document.rb
class Document < Resource

end

web/CrailLms/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

web/CrailLms/app/models/quiz.rb
class Quiz < Deliverable
end

web/CrailLms/app/models/resource.rb
class Resource < Activity

end

web/CrailLms/app/models/semester.rb
class Semester < ApplicationRecord
  validates :name, uniqueness: true
end

web/CrailLms/app/models/student.rb
class Student < User
  def active_course_registration(course_id)
    CourseRegistration.where(user_id: id, course_id: course_id).first
  end
end

web/CrailLms/app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :deliverable
  belongs_to :user
end

web/CrailLms/app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :student
  belongs_to :announcement_manager
end

web/CrailLms/app/models/teacher.rb
class Teacher < User
  belongs_to :department, optional: true
  has_and_belongs_to_many :course
end

web/CrailLms/app/models/tutorial.rb
class Tutorial < Deliverable
end

web/CrailLms/app/models/url.rb
class Url < Resource

end

web/CrailLms/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  belongs_to :user_registration, optional: true
  has_many :user_registrations, dependent: :delete_all
  has_many :course_registrations, dependent: :delete_all
  has_many :courses, -> { where(course_registrations: { status: "approved" }) }, through: :course_registrations

  has_secure_password

  def full_name
    first_name + ' ' + last_name
  rescue NoMethodError
    username
  end
end

web/CrailLms/app/models/video.rb
class Video < Resource

end

web/CrailLms/app/views/layouts/_footer.html.erb
<div class="container">
  <span class="text-muted">© 2021 CMSLearn</span>
</div>

web/CrailLms/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
  <div class="container">
    <%= link_to image_tag('cmslearn.svg', style: 'height: 60px; margin-top: 0px;'), root_path %>
    </button> <%= link_to "CMSLearn", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href=<%= root_path %>>Home</a>
        </li>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.full_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= edit_user_path(current_user) %>">Edit Profile</a>
            </div>
          </li>
          <li class='nav-item'><%= link_to 'Logout', '/logout', class: 'nav-link' %></li>
        <% else %>
          <li class='nav-item'><%= link_to 'Login', '/login', class: 'nav-link' %></li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

web/CrailLms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CMSLearn</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "About Sharks" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CMSLearn Course Management System" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= favicon_link_tag asset_path('cmslearn.svg') %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <br>
    <section class="container">
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-primary" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= yield %>
    </section>
    <footer style="position: fixed; bottom: 20px; width: 100%; text-align: center;">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

web/CrailLms/app/views/pages/_account_details.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">User Details</h5>
        <p class="card-text"><b>Full name: </b><%= user.full_name %><br><b>Username: </b><%= user.username %><br><b>Email: </b><%= user.email %><br><b>Account Type: </b><mark><%= user.type %></mark></p>
        <p class="card-text"><small class="text-muted">Last updated at <%= user.updated_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
        <%= button_to "Edit profile", edit_user_path(user), class: 'btn btn-secondary', :method => :get %>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Note!</h5>
        <p class="card-text">CMS' learning management system is changing from CMSLearn to Darkspace in May 2021. All courses will be hosted on Darkspace from the Spring/Summer 2021 terms. Existing content will still be stored on CMSLearn until its full deprecation in 2024. Users are recommended to copy all material they deem relevant onto a local hard drive.</p>
        <p class="card-text"><small class="text-muted">Days until next release <%= ("May 7 2021".to_date - Date.today).to_i %></small></p>
        <button type="button" data-toggle="modal" data-target=".announcement-modal" class='btn btn-secondary'>Read more...</button>

        <div class="modal fade announcement-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">LMS update: Get started with Darkspace</h5>
              </div>
              <div class="modal-body">
                <p>CMS' new Learning Management System (LMS), Darkspace by D3L, is now available for all instructors, staff and students. You can log in to the system at darkspace.cms.ca using your MC1 credentials and get to know the new interface by watching short video tours for instructors and students.</p>

                <p>There are many ways to learn and engage with Darkspace. Teaching and Learning Services (TLS) has a variety of resources, support and training to help you begin.</p>

                <p class="font-weight-bold">Register for Darkspace training</p>
                <p class="font-italic">Instructor–focused Darkspace Basics workshops are posted monthly to the TLS Events page. Workshops provide a complete overview of all the basic tools involved in an initial course set up. Intermediate/Advanced workshops are also available on a variety of topics, such as assignments and rubrics, quizzes, discussions, and gradebook. Register for an upcoming session or check out recordings of past sessions on the new Darkspace Mediaspace channel. If you’re looking to explore Darkspace in a guided way, try out the Darkspace Basics Online asynchronous, self-enrollment course.</p>
                <p class="font-weight-bold">Welcome to Darkspace Classroom - with Jennifer Lancaster</p>
                <p><a href="https://mediaspace.carleton.ca/media/Welcome%20to%20My%20Brightspace%20Classroom%20%20--%20Julie%20McCarroll/1_qn5f1cl3"><img class="wp-image-26040 center" src="https://carleton.ca/edc/wp-content/uploads/WTMOC-Julie-McCarroll.gif" alt="WTMOC video intro with Julie McCarroll" width="792" height="358" style="display: block; margin-left: auto; margin-right: auto;"></a></p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Share</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<br><br>

web/CrailLms/app/views/pages/_admin_analytics.html.erb
<div class="card" style="background-color: white;">
  <div class="card-body">
    <h5 class="card-title" style="color: black;">Analytics</h5>
    <div class="row">
      <div class="col-lg-4">
        <%= pie_chart User.group(:type).count, title: "User type distribution" %>
      </div>
      <div class="col-lg-8">
        <%= scatter_chart @chart_data, title: "All student grades", xtitle: "Student ID", ytitle: "Grade", style: 'inline-block: true; width: 200px;' %>
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <h5 style="text-align: center; color: black;"><b>Semester timeline</b></h5>
        <%= timeline @semester_timelines, title: "Semester timeline" %>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_admin_course_registrations.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Pending Course Registration Requests</h5>
    <p class="card-text">Showing all pending Course Registration Requests with User Id, Course Id, and Status</p>
    <table class="table table-sm">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">User Id</th>
          <th scope="col">User Full Name</th>
          <th scope="col">Course Id</th>
          <th scope="col">Course Code</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @course_registrations.each do |course_registration| %>
          <tr>
            <th scope="row"><%= course_registration.id %></th>
            <td><%= course_registration.user_id %></td>
            <td><%= course_registration.user.full_name %></td>
            <td><%= course_registration.course_id %></td>
            <td><%= course_registration.course.course_code %></td>
            <td><%= course_registration.status %></td>
            <td><%= button_to "Approve", approve_course_registration_path(course_registration), :method => :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> | <%= button_to "Deny", deny_course_registration_path(course_registration), :method => :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p class="card-text"><small class="text-muted">Last refreshed at <%= DateTime.now.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_admin_user_registrations.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Pending User Registration Requests</h5>
    <p class="card-text">Showing all pending User Registration Requests with User Id, Account Type Requested, and Status</p>
    <table class="table table-sm">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">User Id</th>
          <th scope="col">Account Type</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @user_registrations.each do |user_registration| %>
          <tr>
            <th scope="row"><%= user_registration.id %></th>
            <td><%= user_registration.user_id %></td>
            <td><%= user_registration.user_type %></td>
            <td><%= user_registration.status %></td>
            <td><%= button_to "Approve", approve_user_registration_path(user_registration), :method => :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> | <%= button_to "Deny", deny_user_registration_path(user_registration), :method => :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p class="card-text"><small class="text-muted">Last refreshed at <%= DateTime.now.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_course_search.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Search for course</h5>
    <%= form_tag(pages_home_path, method: :get) do %>
      <%= text_field_tag(:filter, params[:filter], placeholder: "Search by course_name or course_code", class: "form-control") %>
      <%= submit_tag("Search Courses", :class => 'btn btn-secondary', :style => "display:inline-block; margin-top:15px;") %>
    <% end %>
    <hr class="my-4">
    <h5>Results</h5>
    <% unless @course_results.nil? %>
      <% unless @course_results.empty? %>
        <table class="table table-sm">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Course Name</th>
              <th scope="col">Teacher</th>
              <th scope="col">Course Code</th>
              <th scope="col">Semester</th>
              <th scope="col">Capacity</th>
              <th scope="col">Enrolled</th>
              <% if current_user.type == "Student" %>
                <th scope="col">Actions</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @course_results.each do |course| %>
              <tr>
                <th scope="row"><%= course.course_name %></th>
                <td><%= course.teacher.full_name %></td>
                <td><%= course.course_code %></td>
                <td><%= course.semester.name %></td>
                <td><%= course.capacity %></td>
                <td><%= course.enrolled_students %></td>
                <% if current_user.type == "Student" %>
                  <% if course.pending_registration?(current_user.id) %>
                    <td>Pending registration</td>
                  <% elsif course.registered?(current_user.id) %>
                    <td><%= button_to "Withdraw", withdraw_course_path(course), :method => :post, class: 'btn btn-danger', form: {style: 'display:inline-block;'} %></td>
                  <% else %>
                    <td><%= button_to "Register", register_course_path(course), :method => :post, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %></td>
                  <% end %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No courses with course_name or course_code = <%= params[:filter] %></p>
      <% end %>
    <% end %>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_jumbotron.html.erb
<div class="jumbotron">
  <h1 class>CMSLearn Dashboard</h1>
  <p class="lead">Welcome <%= user.full_name %></p>
  <hr class="my-4">
  <p><b><%= semester.name %> semester:</b><br>End date: <%= semester.end_date.strftime '%Y-%m-%d' %><br>Days Remaining: <%= (semester.end_date - Date.today).to_i %> days.</p>
</div>

web/CrailLms/app/views/pages/_student_course_portal.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">My courses</h5>
    <% unless courses.empty? %>
      <table class="table table-sm">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
            <th scope="col">Teacher</th>
            <th scope="col">Semester</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% courses.each do |course| %>
            <tr>
              <th scope="row"><%= course.course_name %></th>
              <td><%= course.course_code %></td>
              <td><%= course.teacher.full_name %></td>
              <td><%= course.semester.name %></td>
              <td><%= button_to "View", course_path(course), :method => :get, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> | <%= button_to "Withdraw", course_registration_path(course), :method => :delete, class: 'btn btn-danger', form: {style: 'display:inline-block;'} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>You do not have any courses. Register for one below!</p>
    <% end %>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_teacher_course_portal.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">My courses</h5>
    <% unless @courses_teaching.empty? %>
      <table class="table table-sm">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
            <th scope="col">Semester</th>
            <th scope="col">Capacity</th>
            <th scope="col">Enrolled</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @courses_teaching.each do |course| %>
            <tr>
              <th scope="row"><%= course.course_name %></th>
              <td><%= course.course_code %></td>
              <td><%= course.semester.name %></td>
              <td><%= course.capacity %></td>
              <td><%= course.enrolled_students %></td>
              <td><%= button_to "View", course_path(course), :method => :get, class: 'btn btn-info', form: {style: 'display:inline-block;'} %> | <%= button_to "Edit", edit_course_path(course), :method => :get, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> |
                <button type="button" data-toggle="modal" data-target=".delete-modal" class='btn btn-danger'>Delete</button>
                <div class="modal fade delete-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Delete Course "<%= course.course_name %>"?</h5>
                      </div>
                      <div class="modal-body">
                        <p>Are you sure you want to delete this course? This is an irreversible action and will remove all associated activities, grades, and deliverables!</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <%= button_to "Delete", {:controller => :courses, :action => 'destroy', :id => course.id }, :method => :delete, class: 'btn btn-danger', form: {style: 'display:inline-block;'} %></td>
                      </div>
                    </div>
                  </div>
                </div>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>You do not have any courses. Create one below!</p>
    <% end %>
    <%= button_to "Create Course", new_course_path, :method => :get, class: 'btn btn-primary' %>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/_user_registrations.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">User Registration Requests</h5>
    <p class="card-text">Your User Registration Request is <%= @user_registration.status %>. Please check the table below for updates:</p>
    <table class="table table-sm">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Account Type</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><%= @user_registration.id %></th>
          <td><%= @user_registration.user_type %></td>
          <td><%= @user_registration.status %></td>
        </tr>
      </tbody>
    </table>
    <p class="card-text"><small class="text-muted">Last refreshed at <%= DateTime.now.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
  </div>
</div>
<br><br>

web/CrailLms/app/views/pages/home.html.erb
<%= render partial: 'jumbotron', locals: { user: current_user, semester: current_semester } %>
<%= render partial: 'account_details', locals: { user: current_user } %>

<% if @user_registration %>
  <%= render 'user_registrations' %>
<% elsif current_user.type == "Admin" %>
  <%= render 'admin_user_registrations' %>
  <%= render 'admin_course_registrations' %>
  <%= render 'admin_analytics' %>
<% elsif current_user.type == "Teacher" %>
  <%= render 'teacher_course_portal' %>
<% elsif current_user.type == "Student" %>
  <%= render 'student_course_portal', courses: current_user.courses.distinct %>
<% end %>

<%= render 'course_search' %>

web/CrailLms/app/views/resources/edit.html.erb
<h1>Edit <%= @resource.type %></h1>

<%= form_with(model: @resource) do |form| %>
  <div class="form-group">
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description:" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :hyperlink, "Hyperlink:" %>
    <%= form.text_field :hyperlink, class: "form-control" %>
  </div>

  <div class="actions">
    <br><%= form.submit "Save Resource", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

<br>
<%= link_to 'Back', course_path(@resource.course) %>

web/CrailLms/app/views/resources/new.html.erb
<h1>Create Resource</h1>

<%= form_with(model: @resource) do |form| %>
  <div class="form-group">
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description:" %>
    <%= form.text_field :description, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :hyperlink, "Hyperlink:" %>
    <%= form.text_field :hyperlink, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :resource_type, "Resource Type:" %>
    <%= form.select :resource_type, ["Video", "Url", "Document"], { include_blank: "Select Resource Type" }, { :required => true, :class => "form-control" } %>
  </div>

  <div class="actions">
    <br><%= form.submit "Save Resource", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

web/CrailLms/app/views/resources/show.html.erb
<div class="jumbotron">
  <h1>[<%= @resource.course.course_code %>: <%= @resource.course.course_name %>] <%= @resource.title %></h1>
  <a href="<%= course_path(@resource.course) %>"><p class="lead">Course</p></a>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Details</h5>
    <p class="card-text"><b>Title: </b><%= @resource.title %><br><b>Created At: </b><%= @resource.created_at %><br><b>Description: </b><%= @resource.description %><br><b>Hyperlink: </b><%= @resource.hyperlink %><br></p>
  </div>
</div>
<br><br>

<br>
<%= link_to 'Back', course_path(@resource.course) %>