web/CrailLms/config/routes.rb
Rails.application.routes.draw do

  resources :announcements, except: [:index, :show]

  resources :deliverables, except: [:index]
  resources :assignments, controller: 'deliverables', type: 'Assignment'
  resources :quizzes, controller: 'deliverables', type: 'Quiz'
  resources :tutorials, controller: 'deliverables', type: 'Tutorial'

  resources :resources, except: [:index]
  resources :urls, controller: 'resources', type: 'Url'
  resources :videos, controller: 'resources', type: 'Video'
  resources :documents, controller: 'resources', type: 'Document'

  resources :course_registrations do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :user_registrations do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :courses do
    post 'register', on: :member
    post 'withdraw', on: :member
    post 'create_announcement', on: :member
    post 'update_grade', on: :member
  end

  resources :users
  resources :teachers, controller: 'users', type: 'Teacher'
  resources :admins, controller: 'users', type: 'Admin'
  resources :students, controller: 'users', type: 'Student'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'pages/home'

  root to: 'pages#home'
end

web/CrailLms/app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :course
  self.abstract_class = true
end

web/CrailLms/app/models/admin.rb
class Admin < User
end

web/CrailLms/app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :announcement_manager
end

web/CrailLms/app/models/assignment.rb
class Assignment < Deliverable
end

web/CrailLms/app/models/course.rb
class Course < ApplicationRecord
  belongs_to :semester
  belongs_to :teacher
  has_many :course_registrations, dependent: :delete_all
  has_many :users, -> { where(course_registrations: { status: "approved" }) }, through: :course_registrations
  has_many :deliverables
  has_many :resources
  has_many :announcements
  has_one :announcement_manager
  after_create :setup_announcement_manager

  def enrolled_students
    CourseRegistration.where(course_id: id, status: "approved").count
  end

  def pending_registration?(user_id)
    !CourseRegistration.where(course_id: id, user_id: user_id, status: "pending").empty?
  end

  def registered?(user_id)
    !CourseRegistration.where(course_id: id, user_id: user_id, status: "approved").empty?
  end

  def setup_announcement_manager
    create_announcement_manager
    self.announcement_manager_id = AnnouncementManager.last.id
  end
end

web/CrailLms/app/models/deliverable.rb
class Deliverable < Activity
  has_many :submissions, dependent: :delete_all
end

web/CrailLms/app/models/department.rb
class Department < ApplicationRecord
  has_many :course
  has_many :teacher
end

web/CrailLms/app/models/document.rb
class Document < Resource

end

web/CrailLms/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

web/CrailLms/app/models/quiz.rb
class Quiz < Deliverable
end

web/CrailLms/app/models/resource.rb
class Resource < Activity

end

web/CrailLms/app/models/semester.rb
class Semester < ApplicationRecord
  validates :name, uniqueness: true
end

web/CrailLms/app/models/student.rb
class Student < User
  def active_course_registration(course_id)
    CourseRegistration.where(user_id: id, course_id: course_id).first
  end
end

web/CrailLms/app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :deliverable
  belongs_to :user
end

web/CrailLms/app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :student
  belongs_to :announcement_manager
end

web/CrailLms/app/models/teacher.rb
class Teacher < User
  belongs_to :department, optional: true
  has_and_belongs_to_many :course
end

web/CrailLms/app/models/tutorial.rb
class Tutorial < Deliverable
end

web/CrailLms/app/models/url.rb
class Url < Resource

end

web/CrailLms/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  belongs_to :user_registration, optional: true
  has_many :user_registrations, dependent: :delete_all
  has_many :course_registrations, dependent: :delete_all
  has_many :courses, -> { where(course_registrations: { status: "approved" }) }, through: :course_registrations

  has_secure_password

  def full_name
    first_name + ' ' + last_name
  rescue NoMethodError
    username
  end
end

web/CrailLms/app/models/video.rb
class Video < Resource

end

web/CrailLms/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authorized
  before_action :set_session_course, :set_course, only: %i[ show edit update destroy register withdraw ]

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params.except(:announcement_content))
    @course.teacher = current_user
    @course.semester = current_semester

    if @course.save
      flash[:notice] = "Course successfully created."
      redirect_to root_path
    else
      flash[:error] = @course.errors
      redirect_to new_course_path
    end
  end

  def show
    if current_user.type == "Student"
      course_registration = CourseRegistration.find_by!(status: "approved", user: current_user, course: @course)
      @grade = course_registration.grade
    end
  end

  def update_grade
    course_registration = CourseRegistration.find_by!(status: "approved", user: Student.find_by!(username: params[:username]))
    course_registration.update!(grade: params[:updated_grade])

    flash[:notice] = "Student with username=#{params[:username]} grade succesfully updated"
    redirect_back fallback_location: root_path
  end

  def register
    create_course_registration
  rescue
    flash[:error] = "Error creating course registration"
    redirect_to root_path
  else
    flash[:notice] = "Course #{@course.course_code} successfully registered. An admin will review your request shortly."
    redirect_to root_path
  end

  def withdraw
    course_registration = CourseRegistration.find_by!(status: "approved", user: current_user, course: @course)

    if course_registration
      course_registration.update!(status: "withdrawn")
      flash[:notice] = "Course #{@course.course_code} successfully withdrawn."
      redirect_to root_path
    end
  end

  def create_announcement
    course = Course.find(session[:course_id])
    announcement_manager = AnnouncementManager.find(session[:course_id])
    announcement = announcement_manager.announcements.build(announcement_content: params[:announcement_content])
    announcement.save
    announcement = Announcement.last
    course.announcement_manager.notify(announcement)
    flash[:notice] = "Announcement successfully created."
    redirect_to course_path(course)
  end

  def update
    if @course.update(course_params)
      flash[:notice] = "Course successfully updated."
      redirect_to course_path(@course)
    else
      flash[:notice] = @course.errors
      redirect_to edit_course_path(@course)
    end
  end

  def destroy
    @course.destroy
    flash[:notice] = "Course successfully deleted."
    redirect_to root_path
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def set_session_course
    session[:course_id] = params[:id]
  end

  def course_params
    params.require(:course).permit(:course_name, :course_code, :capacity, :announcement_content)
  end

  def create_course_registration
    CourseRegistration.create!(status: "pending", user: current_user, course: @course)
  end
end

web/CrailLms/app/views/courses/_admin_view.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Teacher Details</h5>
        <p class="card-text"><b>Full name: </b><%= @course.teacher.full_name %><br><b>Username: </b><%= @course.teacher.username %><br><b>Email: </b><%= @course.teacher.email %><br></p>
        <p class="card-text"><small class="text-muted">Last updated at <%= @course.teacher.updated_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
        <%= button_to "Edit profile", edit_user_path(current_user), class: 'btn btn-secondary', :method => :get %>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Course Info</h5>
        <p class="card-text"><b>Course Name: </b><%= @course.course_name %><br><b>Course Code: </b><%= @course.course_code %><br><b>Capacity: </b><%= @course.enrolled_students %>/<%= @course.capacity %> [<mark><%= @course.capacity - @course.enrolled_students %> spots remaining</mark>]<br></p>
        <p class="card-text"><small class="text-muted">Last updated at <%= @course.updated_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></small></p>
        <%= button_to "Edit course", edit_course_path(@course), class: 'btn btn-secondary', :method => :get %>
      </div>
    </div>
  </div>
</div>
</div>
<br><br>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Resources</h5>
        <% unless @course.resources.empty? %>
          <table class="table table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Created At</th>
                <th scope="col">Type</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @course.resources.each do |resource| %>
                <tr>
                  <th scope="row"><%= resource.title %></th>
                  <td><%= resource.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
                  <td><%= resource.type %></td>
                  <td><%= button_to "View", resource_path(resource), :method => :get, class: 'btn btn-info', form: {style: 'display:inline-block;'} %> | <%= button_to "Edit", edit_resource_path(resource), :method => :get, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> |
                    <button type="button" data-toggle="modal" data-target=".delete-modal" class='btn btn-danger'>Delete</button>
                    <div class="modal fade delete-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">Delete Resource "<%= resource.title %>"?</h5>
                          </div>
                          <div class="modal-body">
                            <p>Are you sure you want to delete this resource? This is an irreversible action!</p>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <%= button_to "Delete", {:controller => :resources, :action => 'destroy', :id => resource.id }, :method => :delete, class: 'btn btn-danger', form: {style: 'display:inline-block;'} %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>There are no resources created for this course.</p>
        <% end %>
        <%= button_to "Create Resource", new_resource_path, class: 'btn btn-primary', :method => :get %>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Deliverables</h5>
        <% unless @course.deliverables.empty? %>
          <table class="table table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Due Date</th>
                <th scope="col">Type</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @course.deliverables.each do |deliverable| %>
                <tr>
                  <th scope="row"><%= deliverable.title %></th>
                  <td><%= deliverable.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
                  <td><%= deliverable.type %></td>
                  <td> <%= button_to "View", deliverable_path(deliverable), :method => :get, class: 'btn btn-info', form: {style: 'display:inline-block;'} %> | <%= button_to "Edit", edit_deliverable_path(deliverable), :method => :get, class: 'btn btn-primary', form: {style: 'display:inline-block;'} %> |
                    <button type="button" data-toggle="modal" data-target=".delete-modal" class='btn btn-danger'>Delete</button>
                    <div class="modal fade delete-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">Delete Deliverable "<%= deliverable.title %>"?</h5>
                          </div>
                          <div class="modal-body">
                            <p>Are you sure you want to delete this deliverable? This is an irreversible action and will remove all associated submissions!</p>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <%= button_to "Delete", {:controller => :deliverables, :action => 'destroy', :id => deliverable.id }, :method => :delete, class: 'btn btn-danger', form: {style: 'display:inline-block;'} %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>There are no deliverables created for this course.</p>
        <% end %>
        <%= button_to "Create Deliverable", new_deliverable_path, class: 'btn btn-primary', :method => :get %>
      </div>
    </div>
  </div>
</div>
<br><br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Students</h5>
    <% unless @course.users.empty? %>
      <table class="table table-sm">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Full Name</th>
            <th scope="col">Username</th>
            <th scope="col">Registered At</th>
            <th scope="col">Grade</th>
          </tr>
        </thead>
        <tbody>
          <% @course.users.each do |student| %>
            <tr>
              <th scope="row"><%= student.full_name %></th>
              <td><%= student.username %></td>
              <td><%= student.active_course_registration(@course.id).created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
              <td><%= student.active_course_registration(@course.id).grade %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are no students registered for this course.</p>
    <% end %>
    <h5>Update Student Grade</h5>
    <%= form_tag(update_grade_course_path, method: :post, class:"form-inline") do %>
      <div style="display:block">
        <%= text_field_tag(:username, params[:username], placeholder: "Student username", class: "form-control") %>
        <%= text_field_tag(:updated_grade, params[:updated_grade], placeholder: "Updated Grade", class: "form-control") %>
        <%= submit_tag("Update", :class => 'btn btn-primary', :style => "margin-left: 8px;") %>
      </div>
    <% end %>
  </div>
</div>
<br><br>

web/CrailLms/app/views/courses/_announcements.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Announcements</h5>
    <% unless @course.announcement_manager.announcements.empty? %>
      <table class="table table-sm">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Announcement</th>
            <th scope="col">Message</th>
            <th scope="col">Created On</th>
          </tr>
        </thead>
        <tbody>
          <% @course.announcement_manager.announcements.each do |announcement| %>
            <tr>
              <th scope="row"><%= announcement.id %></th>
              <th scope="row"><%= announcement.announcement_content %></th>
              <th scope="row"><%= announcement.created_at.to_formatted_s(:long_ordinal) %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>There are currently no announcements for this course.</p>
    <% end %>
    <% if current_user.type == "Teacher" %>
      <%= form_tag(create_announcement_course_path, method: :post) do %>
        <%= text_field_tag(:announcement_content, params[:announcement_content], placeholder: "Enter announcement content", class: "form-control") %>
        <%= submit_tag("Create Announcement", :class => 'btn btn-primary', :style => "display:inline-block; margin-top:15px;") %>
      <% end %>
    <% end %>
  </div>
</div>
<br><br>

web/CrailLms/app/views/courses/_jumbotron.html.erb
<div class="jumbotron">
  <h1 class>[<%= @course.semester.name %>] <%= @course.course_code %>: <%= @course.course_name %></h1>
  <a href="/"><p class="lead">Dashboard</p></a>
</div>

web/CrailLms/app/views/courses/_student_view.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Teacher Details</h5>
        <p class="card-text"><b>Full name: </b><%= @course.teacher.full_name %><br><b>Username: </b><%= @course.teacher.username %><br><b>Email: </b><%= @course.teacher.email %><br></p>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Course Info</h5>
        <p class="card-text"><b>Course Name: </b><%= @course.course_name %><br><b>Course Code: </b><%= @course.course_code %><br><b>Capacity: </b><%= @course.enrolled_students %>/<%= @course.capacity %> [<mark><%= @course.capacity - @course.enrolled_students %> spots remaining</mark>]<br></p>
      </div>
    </div>
  </div>
</div>
</div>
<br><br>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Resources</h5>
        <% unless @course.resources.empty? %>
          <table class="table table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Created At</th>
                <th scope="col">Type</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @course.resources.each do |resource| %>
                <tr>
                  <th scope="row"><%= resource.title %></th>
                  <td><%= resource.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
                  <td><%= resource.type %></td>
                  <td><%= button_to "View", resource_path(resource), :method => :get, class: 'btn btn-info', form: {style: 'display:inline-block;'} %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>There are no resources created for this course.</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Deliverables</h5>
        <% unless @course.deliverables.empty? %>
          <table class="table table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Weight</th>
                <th scope="col">Due Date</th>
                <th scope="col">Type</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @course.deliverables.each do |deliverable| %>
                <tr>
                  <th scope="row"><%= deliverable.title %></th>
                  <td><%= deliverable.weight %></td>
                  <td><%= deliverable.created_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></td>
                  <td><%= deliverable.type %></td>
                  <td> <%= button_to "View", deliverable_path(deliverable), :method => :get, class: 'btn btn-info', form: {style: 'display:inline-block;'} %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>There are no deliverables created for this course.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br><br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Timeline</h5>
  </div>
</div>
<br><br>

<div class="card">
  <div class="card-body">
    <p class="card-text">Your current grade for this course is: <%= @grade %></p>
  </div>
</div>

web/CrailLms/app/views/courses/edit.html.erb
<h1>Edit Course</h1>
<%= form_with(model: @course) do |form| %>
  <div class="form-group">
    <%= form.label :course_name, "Course Name:" %>
    <%= form.text_field :course_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :course_code, "Course Code:" %>
    <%= form.text_field :course_code, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :capacity, "Capacity:" %>
    <%= form.number_field :capacity, in: 1..5000, step: 1, required: true, class: "form-control" %>
  </div>

  <div class="actions">
    <br><%= form.submit "Update Course", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

web/CrailLms/app/views/courses/new.html.erb
<h1>Create Course</h1>
<%= form_with(model: @course) do |form| %>
  <div class="form-group">
    <%= form.label :course_name, "Course Name:" %>
    <%= form.text_field :course_name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :course_code, "Course Code:" %>
    <%= form.text_field :course_code, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :capacity, "Capacity:" %>
    <%= form.number_field :capacity, in: 1..5000, step: 1, required: true, class: "form-control" %>
  </div>

  <div class="actions">
    <br><%= form.submit "Create Course", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

web/CrailLms/app/views/courses/show.html.erb
<%= render 'jumbotron' %>
<%= render 'announcements' %>

<% if current_user.type == "Student" %>
  <%= render 'student_view' %>
<% else %>
  <%= render 'admin_view' %>
<% end %>